### ISSUE TITLE
start subset of processes

### ISSUE THREAD

**Issue by mamachanko** [ddollar/forego#57] opened 2015-05-28 09:55 UTC
`forego` doesn't allow to start a subset of processes, like `foreman` does.

Given this `Procfile`:
```
web: ./runweb.sh
worker: ./runworker.sh
db: ./rundb.sh
```

One can run two web processes and one worker with `foreman` like so:
```
$ foreman start web=2,worker=1
web.1 ...
web.2 ...
worker.1 ...
....
```
There's no need to specify `db=0`.

However, `forego` will always run the entire set of processes:
```
$ forego start -c web=2,worker=1
web.1 ...
web.2 ...
worker.1 ...
db.1 ...
...
```

It's possible to limit to one process name with `forego start -c web=2,worker=1 web`, but I'd like to run a subset as with `foreman`.

Am I simply not able to figure out the the right way to do it or is it not supported?

**Comment by mamachanko** [comment] 2015-05-28 09:56
Well, I understand that I could do it by explicitely skipping certain processes(e.g. `db=0`), but I'd have to list all of them and that is painful for >3 services.

**Comment by bjrbhre** [comment] 2015-09-22 13:40
:+1: for the issue / regression vs. foreman.

@mamachanko to avoid listing all processes, you can simply type `all=0` (see [here](https://github.com/ddollar/forego/blob/master/start.go#L239-L241) in the source).

For example, if your Procfile looks like this:
```
web:  ...
db: ...
worker: ...
```

You can start only web + worker by typing:
```
forego start -c all=0,web=1,worker=2
```

This is not as nice as it currently is in foreman but in the meantime, it does the job.

**Comment by ddollar** [comment] 2016-04-30 19:02
Going to close this issue for now since it's working as intended but I would accept this as a pull request if anyone is feeling up to it!

**Closed by ddollar** 2016-04-30 19:02 UTC
Labels: enhancement
